// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WIN.AGDATA.WIN.Infrastructure.Data;

#nullable disable

namespace INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Events.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Events.EventParticipant", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ParticipatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_EventParticipants_UserId");

                    b.ToTable("EventParticipants", (string)null);
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Redemptions.Redemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Redemptions", (string)null);
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Transactions.PointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EventId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid?>("RedemptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PointsTransactions", (string)null);
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Events.Event", b =>
                {
                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Events.EventInfo", "Info", b1 =>
                        {
                            b1.Property<string>("EventId")
                                .HasColumnType("nvarchar(20)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Info_CreatedAt");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Info_Description");

                            b1.Property<DateTime>("EventDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Info_EventDate");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Info_Name");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Events.EventStatus", "Status", b1 =>
                        {
                            b1.Property<string>("EventId")
                                .HasColumnType("nvarchar(20)");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Status_CompletedAt");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Status_CreatedAt");

                            b1.Property<DateTime?>("DeactivatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Status_DeactivatedAt");

                            b1.Property<string>("DeactivationReason")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Status_DeactivationReason");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasColumnName("Status_IsActive");

                            b1.Property<bool>("IsCompleted")
                                .HasColumnType("bit")
                                .HasColumnName("Status_IsCompleted");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");

                            b1.OwnsMany("WIN.AGDATA.WIN.Domain.Entities.Events.Winner", "Winners", b2 =>
                                {
                                    b2.Property<string>("EventStatusEventId")
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("EmployeeId")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("EmployeeId");

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int")
                                        .HasColumnName("Rank");

                                    b2.Property<DateTime>("WonAt")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("WonAt");

                                    b2.HasKey("EventStatusEventId", "Id");

                                    b2.ToTable("Winner", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EventStatusEventId");
                                });

                            b1.Navigation("Winners");
                        });

                    b.OwnsMany("WIN.AGDATA.WIN.Domain.Entities.Events.PrizeTier", "Prizes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("EventId")
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Description")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Description");

                            b1.Property<int>("Points")
                                .HasColumnType("int")
                                .HasColumnName("Points");

                            b1.Property<int>("Rank")
                                .HasColumnType("int")
                                .HasColumnName("Rank");

                            b1.HasKey("Id", "EventId");

                            b1.HasIndex("EventId");

                            b1.ToTable("PrizeTier", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Prizes");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Events.EventParticipant", b =>
                {
                    b.HasOne("WIN.AGDATA.WIN.Domain.Entities.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WIN.AGDATA.WIN.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Products.Product", b =>
                {
                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Products.ProductIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Identity_Description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Identity_Name");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Products.ProductInventory", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("LastStockUpdate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Inventory_LastStockUpdate");

                            b1.Property<int>("StockQuantity")
                                .HasColumnType("int")
                                .HasColumnName("Inventory_StockQuantity");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Products.ProductPoints", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Pricing_LastUpdated");

                            b1.Property<int>("RequiredPoints")
                                .HasColumnType("int")
                                .HasColumnName("Pricing_RequiredPoints");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Redemptions.Redemption", b =>
                {
                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Redemptions.RedemptionStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ApprovedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Status_ApprovedAt");

                            b1.Property<DateTime?>("DeliveredAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Status_DeliveredAt");

                            b1.Property<string>("RejectionReason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Status_RejectionReason");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Status_Value");

                            b1.HasKey("Id");

                            b1.ToTable("Redemptions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("WIN.AGDATA.WIN.Domain.Entities.Users.User", b =>
                {
                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Users.UserIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Identity_Email");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Identity_EmployeeId");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Identity_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Identity_LastName");

                            b1.HasKey("UserId");

                            b1.HasIndex("Email")
                                .IsUnique()
                                .HasDatabaseName("IX_Users_Email");

                            b1.HasIndex("EmployeeId")
                                .IsUnique()
                                .HasDatabaseName("IX_Users_EmployeeId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Users.UserPoints", "Points", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CurrentBalance")
                                .HasColumnType("int")
                                .HasColumnName("Points_CurrentBalance");

                            b1.Property<int>("EarnedPoints")
                                .HasColumnType("int")
                                .HasColumnName("Points_EarnedPoints");

                            b1.Property<int>("SpentPoints")
                                .HasColumnType("int")
                                .HasColumnName("Points_SpentPoints");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("WIN.AGDATA.WIN.Domain.Entities.Users.UserStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeactivatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("Status_DeactivatedAt");

                            b1.Property<string>("DeactivationReason")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Status_DeactivationReason");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasColumnName("Status_IsActive");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Points")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
